version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./static/:/code/static/
      - ./media/:/code/media/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "always"
    volumes:
      - /data/mysql/:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auctionDB
      MYSQL_PASSWORD: 123456

  web:
    container_name: "models_project"
    build: .
    restart: always
    volumes:
      - .:/code
      - ./static/:/code/static/
      - ./media/:/code/media/
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - TIMEOUT=300
      - HTTP_PORT=8000
      - STATS_PORT=8001
      - LANG=C.UTF-8
      - LANG en_US.UTF-8
      - LANGUAGE en_US:en
      - LC_ALL en_US.UTF-8
    ports:
      - 8000:8000
    depends_on:
      - db

